### ISSUE TITLE
Testing the Pack

### ISSUE THREAD

**Issue by MayorRon** [TacticalUniverse/Land-of-Survival-2#1]
Ok.  I figured out mining and can now get Iron (so I can make torches).  But I need to make an Iron Bucket.  Two recipies to make one both require the Smeltery.  The Smeltery seared bricks require Soul Sand from the Nether and the cake for the Nether requires Obsidion.  Without torches, I cannot mine Diamonds to harvest Obsidion and without a bucket I cannot make it.  Is there a pathway to torches or Iron Buckets I am missing?  If so, then a hint would be appreciated.  If not, is this an issue?  Please let me know.

**Comment by TacticalUniverse** [comment]
Replace Iron plates on the bucket to Iron Casing from AA
