### ISSUE TITLE
Breaking Pam's Frost Garden crashes game to desktop.

### ISSUE THREAD

**Issue by remclave** [TacticalUniverse/Land-of-Survival-2#2]
duplicated. Edited to add: it appears all of Pam's gardens crash to desktop.
crash report:
[crash-2018-06-23_19.04.33-client.txt](https://github.com/TacticalUniverse/Land-of-Survival-2/files/2130339/crash-2018-06-23_19.04.33-client.txt)

**Comment by TacticalUniverse** [comment]
Reported to mod dev
